#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Program that shows use of setMotorSyncEncoder in 2 custom made functions.

void drive(long nMotorRatio, long dist, long motorPower);
void turn90(long nMotorRatio, long motorPower);

task main()
{
	drive(0, 100, 50); // Drive forward 100cm at 50 speed
	turn90(-100, 30);    // Turn 90 degrees with 30 speed
}

void drive(long nMotorRatio, long dist, long motorPower)
{ // Function that drives wheels on specified distance in centimeters. Function also takes nMotorRatio and motor power as arguments.
		float wheelDiameter = 5.5; // In cm
		float distanceInOneRotation = wheelDiameter * PI; //2*R*PI
		long rotations = dist / distanceInOneRotation; // How many full wheel rotations are in given distance
		setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 360 * rotations, motorPower);
		waitUntilMotorStop(leftMotor);
		waitUntilMotorStop(rightMotor);
}

void turn90(long nMotorRatio, long motorPower)
{ // Turn 90 degrees in specified direction and power
		setMotorSyncEncoder(rightMotor, leftMotor, nMotorRatio, 180, motorPower);
		waitUntilMotorStop(rightMotor);
		waitUntilMotorStop(leftMotor);
}
