#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Program that drives robot forward for a specified distance that can be chosen by user in robot's menu screen.


void drive(long nMotorRatio, long dist, long motorPower);

task main()
{
	short menuPosition = 0;
	long distanceToTravel;
	bool buttonPressed = false;
	bool buttonEnterPressed = false;

	while (true)
	{
		// Clear display every frame
		eraseDisplay();
		// If buttonIp is pressed, increment menu position, else decrement menu position.
		// Check if menuPosition is not out of its bounds (0-3).
		if(getButtonPress(buttonUp) && !buttonPressed)
		{
		buttonPressed = true;
			menuPosition--;
			if(menuPosition < 0)
				menuPosition = 0;
		}
		if(getButtonPress(buttonDown) && !buttonPressed)
		{
			buttonPressed = true;
			menuPosition++;
			if(menuPosition > 3)
				menuPosition = 3;
		}

		// Display current menu position based on user input.
		switch(menuPosition)
		{
			case 0:
					displayCenteredBigTextLine(1, ">10cm<");
					displayCenteredBigTextLine(3, "40cm");
					displayCenteredBigTextLine(5, "60cm");
					displayCenteredBigTextLine(7, "80cm");
					distanceToTravel = 10.0;
					break;
			case 1:
					displayCenteredBigTextLine(1, "10cm");
					displayCenteredBigTextLine(3, ">40cm<");
					displayCenteredBigTextLine(5, "60cm");
					displayCenteredBigTextLine(7, "80cm");
					distanceToTravel = 40.0;
					break;
			case 2:
					displayCenteredBigTextLine(1, "10cm");
					displayCenteredBigTextLine(3, "40cm");
					displayCenteredBigTextLine(5, ">60cm<");
					displayCenteredBigTextLine(7, "80cm");
					distanceToTravel = 60.0;
					break;
			case 3:
					displayCenteredBigTextLine(1, "10cm");
					displayCenteredBigTextLine(3, "40cm");
					displayCenteredBigTextLine(5, "60cm");
					displayCenteredBigTextLine(7, ">80cm<");
					distanceToTravel = 80.0;
					break;
		}

		// If button enter pressed, start moving forward basing on menu option chosen by user.
		if(getButtonPress(buttonEnter) && !buttonEnterPressed)
		{
			buttonEnterPressed = true;
			drive(0, distanceToTravel, 50);
		}

		// Check if buttons are released
		if(!getButtonPress(buttonDown) || !getButtonPress(buttonUp))
		{
			buttonPressed = false;
		}

		if(!getButtonPress(buttonEnter))
		{
			buttonEnterPressed = false;
		}
		// Wait 250 ms, this gives us 50 readings per second.
		sleep(250);
	}
}

void drive(long nMotorRatio, long dist, long motorPower)
{ // Function that drives wheels on specified distance in centimeters. Function also takes nMotorRatio and motor power as arguments.
		float wheelDiameter = 5.5; // In cm
		float distanceInOneRotation = wheelDiameter * PI; //2*R*PI
		float rotations = dist / distanceInOneRotation; // How many full wheel rotations are in given distance
		setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 360 * rotations, motorPower);
		waitUntilMotorStop(leftMotor);
		waitUntilMotorStop(rightMotor);
}
