#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Program that drives robot forward, turn 180 degrees and go back to start position(using setMotorSyncEncoder).

void drive(long nMotorRatio, long dist, long motorPower);
void turn180(long nMotorRatio, long motorPower);

task main()
{
	drive(0, 100, 100); // Go forward 100cm at 100 speed
	turn180(-100, 15); // Turn right 90 degrees
	drive(0, 100, 25); // Go forward 100cm at 25 speed;
}

void drive(long nMotorRatio, long dist, long motorPower)
{ // Function that drives wheels on specified distance in centimeters. Function also takes nMotorRatio and motor power as arguments.
		float wheelDiameter = 5.5; // In cm
		float distanceInOneRotation = wheelDiameter * PI; //2*R*PI
		long rotations = dist / distanceInOneRotation; // How many full wheel rotations are in given distance
		setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 360 * rotations, motorPower);
		waitUntilMotorStop(leftMotor);
		waitUntilMotorStop(rightMotor);
}

void turn180(long nMotorRatio, long motorPower)
{ // Turn 90 degrees in specified direction and power
		setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 360, motorPower);
		waitUntilMotorStop(leftMotor);
		waitUntilMotorStop(rightMotor);
}
