#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S4,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool startTurningLeft = false;

	/* Calibrate gyro sensor */
	resetGyro(gyroSensor);
	sleep(300);

	while(true)
	{
		/* Start turning arm motor */
		if(!startTurningLeft)
		{
			setMotorSpeed(armMotor, 2);
		}
		else
		{
			setMotorSpeed(armMotor, -2);
		}

		/* Standardize motorSpeed value between 0 and 100 */
		float motorSpeed = getGyroDegrees(gyroSensor) + 50.0;
		setMotorSync(motorB, motorC, 0, motorSpeed);
		displayCenteredBigTextLine(3, "%f", getGyroDegrees(gyroSensor));

		/* Check if position of gyro sensor in degrees is between bounds(-50, 50)
		 * and basing on that, set logic value to a flag that controls arm motor direction
		 */
		if(getGyroDegrees(gyroSensor) > 50)
		{
			startTurningLeft = true;
		}

		if(getGyroDegrees(gyroSensor) < -50)
		{
			startTurningLeft = false;
		}

		wait1Msec(10);
	}
}
