#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S4,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turnLeft90();
void turnRight90();
void drive(long nMotorRatio, long dist, long motorPower);

// STARTING POSITION
const short startXPos = 1;
const short startYPos = 4;

task main()
{
	bool positionSet = false;
	short menuPos = 0;
	long gridWidth = 16;
	short xPos, yPos;									// Target position
	short currentXPos = startXPos;		// Current robot x position on grid
	short currentYPos = startYPos;		// Current robot y position on grid

	/* Choose destination in menu */
	while(!positionSet)
	{
		if(menuPos == 0)
			displayCenteredTextLine(3, "Position: 4, 1");
		else
			displayCenteredTextLine(3, "Position: 5, 6");

		if(getButtonPress(buttonEnter))
		{
			if(menuPos == 0)
			{
				xPos = 4;
				yPos = 1;
			}
			else
			{
				xPos = 5;
				yPos = 6;
			}

			positionSet = true;
		}

		if(getButtonPress(buttonUp))
		{
			eraseDisplay();
			menuPos = 0;
		}
		else if(getButtonPress(buttonDown))
		{
			eraseDisplay();
			menuPos = 1;
		}
	}
 	/* Display target position */
	eraseDisplay();
	displayCenteredTextLine(2, "Target position: (%d, %d)", xPos, yPos);
	sleep(2000);

	/* Move to target position in X axis */
	int i;
	for(i = startXPos; i < xPos; i++)
	{
		drive(0, gridWidth, 30);
		currentXPos++;
		eraseDisplay();
		displayCenteredBigTextLine(3, "(%d, %d)", currentXPos, currentYPos);
		sleep(200);
	}

	/* Turn left or right basing on target y axis position */
	/* Move to target position in Y axis */
	if(yPos > startYPos)
	{
		turnLeft90();
		sleep(1000);
		for(i = startYPos; i < yPos; i++)
		{
			drive(0, gridWidth, 30);
			currentYPos++;
			eraseDisplay();
			displayCenteredBigTextLine(3, "(%d, %d)", currentXPos, currentYPos);
			sleep(200);
		}
	}
	else
	{
		turnRight90();
		sleep(1000);
		for(i = startYPos; i > yPos; i--)
		{
			drive(0, gridWidth, 30);
			currentYPos--;
			eraseDisplay();
			displayCenteredBigTextLine(3, "(%d, %d)", currentXPos, currentYPos);
			sleep(200);
		}
	}
	sleep(3000);
}

/* Turn left 90 degrees */
void turnLeft90()
{
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);
		resetGyro(gyroSensor);
		sleep(200);
		while(fabs(getGyroDegrees(gyroSensor)) < 80)
		{
			setMotorSpeed(rightMotor, 10);
			setMotorSpeed(leftMotor, -10);
			//displayCenteredBigTextLine(5, "%d@", getGyroDegrees(gyroSensor));
		}
		setMotorSpeed(rightMotor, 0);
		setMotorSpeed(leftMotor, 0);
}

/* Turn right 90 degrees */
void turnRight90()
{
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);
		resetGyro(gyroSensor);
		sleep(200);
		while(fabs(getGyroDegrees(gyroSensor)) < 80)
		{
			setMotorSpeed(rightMotor, -10);
			setMotorSpeed(leftMotor, 10);
			//displayCenteredBigTextLine(5, "%d@", getGyroDegrees(gyroSensor));
		}
		setMotorSpeed(rightMotor, 0);
		setMotorSpeed(leftMotor, 0);
}

/* Function that drives wheels on specified distance in centimeters.
 * Function also takes nMotorRatio and motor power as arguments
 */
void drive(long nMotorRatio, long dist, long motorPower)
{
		float wheelDiameter = 5.5; // In cm
		float distanceInOneRotation = wheelDiameter * PI; //2*R*PI
		float rotations = dist / distanceInOneRotation; // How many full wheel rotations are in given distance
		setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 360 * rotations, motorPower);
		waitUntilMotorStop(leftMotor);
		waitUntilMotorStop(rightMotor);
}
