#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S4,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define OBJECT_COUNT 2
#define MAX_X_GRID 9
#define MAX_Y_GRID 7

void choosePosition(short *posX, short *posY, char *text);
void turnLeft90();
void turnRight90();
void turn180();
void dodgeObject(bool sameRow);
void drive(long nMotorRatio, float dist, long motorPower);

// Width of each grid
const float gridWidth = 15.5;

// STARTING POSITION
short startXPos = 1;
short startYPos = 1;

// DEST POSITION
short destXPos = 1;
short destYPos = 1;

// Target Pos
short objectXPos[OBJECT_COUNT] = {1, 1};
short objectYPos[OBJECT_COUNT] = {1, 1};

task main()
{
  short currentXPos = startXPos;		// Current robot x position on grid
  short currentYPos = startYPos;		// Current robot y position on grid
  short yOffset = 0;

	// Set starting positions
	choosePosition(&startXPos, &startYPos, "Starting");

	// Set destination positions
	choosePosition(&destXPos, &destYPos, "Destination");

	// Set object positions
	choosePosition(&objectXPos[0], &objectYPos[0], "Object 1");

	// Set object positions
	choosePosition(&objectXPos[1], &objectYPos[1], "Object 2");

	/*startXPos = 5;
	startYPos = 5;
	destXPos = 1;
	destYPos = 1;
	objectXPos[0] = 5;
	objectYPos[0] = 3;
	objectXPos[1] = 2;
	objectYPos[1] = 5;*/
	// *****************************************************************************************************

 	/* Display target position */
	eraseDisplay();
	displayCenteredTextLine(2, "Starting position: (%d, %d)", startXPos, startYPos);
	sleep(2000);

	currentXPos = startXPos;
	currentYPos = startYPos;

	/* ****************** Move to target position in X axis ****************** */
	int i, j;
	// Flags that will inform if any object was detected
	bool objectDetected = false;
	bool objectOnSameRow = false;

  if(destXPos > startXPos)
  {
      short finish = destXPos;
      for(i = startXPos; i < finish; i++)
      {
      		// Reset flags on every iteration
      		objectDetected = false;
      		objectOnSameRow = false;
          // Iterate through all object's X position and check if object is close to robot
          for(j = 0; j < OBJECT_COUNT; j++)
          {
              if((currentXPos == objectXPos[j] - 1) && (currentYPos == objectYPos[j]))
              {
                  objectDetected = true;
                  if(objectXPos[j] == destXPos)
                      objectOnSameRow = true;

              }
          }
          if(objectDetected)
          {
              if(objectOnSameRow)
              {
                  dodgeObject(true);
                  finish--;
                  yOffset++;
                  currentXPos++;
                  currentYPos++;
                  // x axis +1
                  // y axis +1
              }
              else
              {
                  dodgeObject(false);
                  finish-=1;
                  currentXPos+=2;
                  // x axis +2
              }
              eraseDisplay();
              displayCenteredBigTextLine(3, "(%d, %d)", currentXPos, currentYPos);
          }
          else
          {
              drive(0, gridWidth, 30);
              currentXPos++;
              eraseDisplay();
              displayCenteredBigTextLine(3, "(%d, %d)", currentXPos, currentYPos);
              sleep(200);
          }
      }
  }
  else if(destXPos < startXPos) // Robot has to go backward from starting point
  {
      turn180();
      short finish = startXPos - destXPos;
      for(i = 0; i < finish; i++)
      {
          for(j = 0; j < OBJECT_COUNT; j++)
          {
              if((currentXPos == objectXPos[j] + 1) && (currentYPos == objectYPos[j]))
              {
                  objectDetected = true;
                  if(objectXPos[j] == destXPos)
                      objectOnSameRow = true;
              }
          }
          if(objectDetected)
          {
              if(objectOnSameRow)
              {
                  dodgeObject(true);
                  finish--;
                  yOffset++;
                  currentXPos--;
                  currentYPos--;
                  // x axis -1
                  // y axis -1
              }
              else
              {
                  dodgeObject(false);
                  finish-=2;
                  currentXPos-=2;
                  // x axis -2
              }
              eraseDisplay();
              displayCenteredBigTextLine(3, "(%d, %d)", currentXPos, currentYPos);
          }
          else
          {
              drive(0, gridWidth, 30);
              currentXPos--;
              eraseDisplay();
              displayCenteredBigTextLine(3, "(%d, %d)", currentXPos, currentYPos);
              sleep(200);
          }

      }
      turn180();
  }

  // Reset variables
  objectDetected = false;
  /* ****************** Move to target position in Y axis ****************** */
  if(destYPos > currentYPos)
  {
      turnRight90();
      // FACING RIGHT
      sleep(1000);
      short finish = destYPos;
      for(i = startYPos; i < destYPos - yOffset; i++)
      {
          for(j = 0; j < OBJECT_COUNT; j++)
          {
              if((currentYPos == objectYPos[j] - 1) && (currentXPos == objectXPos[j]))
                  objectDetected = true;
          }
          if(objectDetected)
          {
                  dodgeObject(false);
                  finish-=2;
                  currentYPos+=2;
                  // y axis +2
                  eraseDisplay();
                  displayCenteredBigTextLine(3, "(%d, %d)", currentXPos, currentYPos);
          }
          else
          {
              drive(0, gridWidth, 30);
              currentYPos++;
              eraseDisplay();
              displayCenteredBigTextLine(3, "(%d, %d)", currentXPos, currentYPos);
              sleep(200);
          }
      }
  }
  else if(destYPos < currentYPos)
  {
      turnLeft90();
      // FACING LEFT
      sleep(1000);
      short finish = destYPos;
      for(i = startYPos + yOffset; i > finish; i--)
      {
          for(j = 0; j < OBJECT_COUNT; j++)
          {
              if((currentYPos == objectYPos[j] - 1) && (currentXPos == objectXPos[j]))
                  objectDetected = true;
          }
          if(objectDetected)
          {
                  dodgeObject(false);
                  finish-=2;
                  currentYPos-=2;
                  // y axis -2
                  eraseDisplay();
                  displayCenteredBigTextLine(3, "(%d, %d)", currentXPos, currentYPos);
          }
          else
          {
              drive(0, gridWidth, 30);
              currentYPos--;
              eraseDisplay();
              displayCenteredBigTextLine(3, "(%d, %d)", currentXPos, currentYPos);
              sleep(200);
          }
      }
  }


	sleep(3000);
}

/* Function that takes two short variables and string as arguments
 * and allows user to set values of that variables by menu on robot's display
*/
void choosePosition(short *posX, short *posY, char *text)
{
	short menuPos 			= 0;
	bool buttonPressed 	= false;
	bool enterPressed 	= false;
	bool xDirectionSet 	= false;
	bool yDirectionSet 	= false;
	bool directionSet 	= false;
	bool prompt = false;

	while(!directionSet)
	{
		if(!xDirectionSet)
		{
			if(!prompt)
			{
				eraseDisplay();
				displayCenteredTextLine(3, "Choose X %s axis position:", text);
				sleep(1500);
				eraseDisplay();
				prompt = true;
			}

			switch(menuPos)
			{
				case 1:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 2:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 3:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 4:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 5:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 6:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 7:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 8:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 9:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
			}

			if(getButtonPress(buttonUp) && !buttonPressed)
			{
				menuPos--;
				if(menuPos < 1)
					menuPos = 1;
				buttonPressed = true;
				eraseDisplay();
			}
			if(getButtonPress(buttonDown) && !buttonPressed)
			{
				menuPos++;
				if(menuPos > 9)
					menuPos = 9;
				buttonPressed = true;
				eraseDisplay();
			}
			if(!getButtonPress(buttonDown) && !getButtonPress(buttonUp)  && buttonPressed)
			{
				buttonPressed = false;
			}

			if(getButtonPress(buttonEnter) && !enterPressed)
			{
				*posX = menuPos;
				enterPressed = true;
				xDirectionSet = true;
				prompt = false;
			}
		}
		else if(!yDirectionSet)
		{
			if(!prompt)
			{
				menuPos = 0;
				eraseDisplay();
				displayCenteredTextLine(3, "Choose Y %s axis position:", text);
				sleep(1500);
				eraseDisplay();
				enterPressed = false;
				buttonPressed = false;
				prompt = true;
			}


			switch(menuPos)
			{
				case 1:
					displayCenteredBigTextLine(3, "X: %d Y: %d", *posX, menuPos);
					break;
				case 2:
					displayCenteredBigTextLine(3, "X: %d Y: %d", *posX, menuPos);
					break;
				case 3:
					displayCenteredBigTextLine(3, "X: %d Y: %d", *posX, menuPos);
					break;
				case 4:
					displayCenteredBigTextLine(3, "X: %d Y: %d", *posX, menuPos);
					break;
				case 5:
					displayCenteredBigTextLine(3, "X: %d Y: %d", *posX, menuPos);
					break;
				case 6:
					displayCenteredBigTextLine(3, "X: %d Y: %d", *posX, menuPos);
					break;
				case 7:
					displayCenteredBigTextLine(3, "X: %d Y: %d", *posX, menuPos);
					break;
			}

			if(getButtonPress(buttonUp) && !buttonPressed)
			{
				menuPos--;
				if(menuPos < 1)
					menuPos = 1;
				buttonPressed = true;
				eraseDisplay();
			}
			if(getButtonPress(buttonDown) && !buttonPressed)
			{
				menuPos++;
				if(menuPos > 7)
					menuPos = 7;
				buttonPressed = true;
				eraseDisplay();
			}
			if(!getButtonPress(buttonDown) && !getButtonPress(buttonUp)  && buttonPressed)
			{
				buttonPressed = false;
			}

			if(getButtonPress(buttonEnter) && !enterPressed)
			{
				*posY = menuPos;
				enterPressed = true;
				xDirectionSet = true;
				directionSet = true;
			}
		}
	}
}

/* Turn left 90 degrees */
void turnLeft90()
{
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);
		resetGyro(gyroSensor);
		sleep(400);
		while(fabs(getGyroDegrees(gyroSensor)) < 87)
		{
			setMotorSpeed(rightMotor, 10);
			setMotorSpeed(leftMotor, -10);
			//displayCenteredBigTextLine(5, "%d@", getGyroDegrees(gyroSensor));
		}
		setMotorSpeed(rightMotor, 0);
		setMotorSpeed(leftMotor, 0);
}

/* Turn right 90 degrees */
void turnRight90()
{
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);
		resetGyro(gyroSensor);
		sleep(400);
		while(fabs(getGyroDegrees(gyroSensor)) < 87)
		{
			setMotorSpeed(rightMotor, -10);
			setMotorSpeed(leftMotor, 10);
			//displayCenteredBigTextLine(5, "%d@", getGyroDegrees(gyroSensor));
		}
		setMotorSpeed(rightMotor, 0);
		setMotorSpeed(leftMotor, 0);
}

/* Turn 180 degrees */
void turn180()
{
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);
		resetGyro(gyroSensor);
		sleep(400);
		while(fabs(getGyroDegrees(gyroSensor)) < 179)
		{
			setMotorSpeed(rightMotor, -10);
			setMotorSpeed(leftMotor, 10);
			//displayCenteredBigTextLine(5, "%d@", getGyroDegrees(gyroSensor));
		}
		setMotorSpeed(rightMotor, 0);
		setMotorSpeed(leftMotor, 0);
}
/*
*/
void dodgeObject(bool sameRow)
{
        if(sameRow == true)
        {
            turnRight90();
			drive(0, gridWidth, 30);
			turnLeft90();
			drive(0, gridWidth, 30); // Drive 2x gridh width to dodge that object
			// Finish facing start direction
        }
        else
        {
            turnRight90();
			drive(0, gridWidth, 30);
			turnLeft90();
			drive(0, 2 * gridWidth, 30); // Drive 2x gridh width to dodge that object
			turnLeft90();
			drive(0, gridWidth, 30); // go back to starting position
			turnRight90();
			// Finish facing start direction
        }
}

/* Function that drives wheels on specified distance in centimeters.
 * Function also takes nMotorRatio and motor power as arguments
 */
void drive(long nMotorRatio, float dist, long motorPower)
{
		float wheelDiameter = 5.5; // In cm
		float distanceInOneRotation = wheelDiameter * PI; //2*R*PI
		float rotations = dist / distanceInOneRotation; // How many full wheel rotations are in given distance
		setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 360 * rotations, motorPower);
		waitUntilMotorStop(leftMotor);
		waitUntilMotorStop(rightMotor);
}
