#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S4,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define OBJECT_COUNT 2
#define MAX_X_GRID 9
#define MAX_Y_GRID 7

void choosePosition(short *posX, short *posY, char *text);
void turnLeft90();
void turnRight90();
void turn180();
void dodgeObject(bool sameRow);
void drive(long nMotorRatio, float dist, long motorPower);

// Width of each grid
const float gridWidth = 15.5;

// STARTING POSITION
short startXPos = 1;
short startYPos = 1;

// DEST POSITION
short destXPos = 1;
short destYPos = 1;

task main()
{
  short currentXPos = startXPos;		// Current robot x position on grid
  short currentYPos = startYPos;		// Current robot y position on grid
  short yOffset = 0;

	startXPos = 3;
	startYPos = 1;
	destXPos = 3;
	destYPos = 7;

	// *****************************************************************************************************

 	/* Display target position */
	eraseDisplay();
	displayCenteredTextLine(2, "Starting position: (%d, %d)", startXPos, startYPos);
	sleep(2000);

	currentXPos = startXPos;
	currentYPos = startYPos;

	/* ****************** Move to target position in X axis ****************** */
	int i, j;
	for(j = 0; j < 2; j++)
	{
	  if(destXPos > startXPos)
	  {
	      short finish = destXPos;
	      for(i = startXPos; i < finish; i++)
	      {
	              drive(0, gridWidth, 30);
	              currentXPos++;
	              eraseDisplay();
	              displayCenteredBigTextLine(3, "(%d, %d)", currentXPos, currentYPos);
	              sleep(200);

	      }
	  }
	  else if(destXPos < startXPos) // Robot has to go backward from starting point
	  {
	      turn180();
	      short finish = startXPos - destXPos;
	      for(i = 0; i < finish; i++)
	      {
	              drive(0, gridWidth, 30);
	              currentXPos--;
	              eraseDisplay();
	              displayCenteredBigTextLine(3, "(%d, %d)", currentXPos, currentYPos);
	              sleep(200);
	      }
	      turn180();
	  }

	  /* ****************** Move to target position in Y axis ****************** */
	  if(destYPos > currentYPos)
	  {
	      turnRight90();
	      // FACING RIGHT
	      sleep(1000);
	      short finish = destYPos;
	      for(i = startYPos; i < destYPos - yOffset; i++)
	      {
	              drive(0, gridWidth, 30);
	              currentYPos++;
	              eraseDisplay();
	              displayCenteredBigTextLine(3, "(%d, %d)", currentXPos, currentYPos);
	              sleep(200);
	      }
	  }
	  else if(destYPos < currentYPos)
	  {
	      turnLeft90();
	      // FACING LEFT
	      sleep(1000);
	      short finish = destYPos;
	      for(i = startYPos + yOffset; i > finish; i--)
	      {
	              drive(0, gridWidth, 30);
	              currentYPos--;
	              eraseDisplay();
	              displayCenteredBigTextLine(3, "(%d, %d)", currentXPos, currentYPos);
	              sleep(200);
	      }
	  }
	  // Back to facing forward
	  turnLeft90();
	  // start beeping for 5000ms
	  int StartTime, myTime;
		StartTime=nSysTime;
		myTime=nSysTime-StartTime;

		while(myTime < 5000)
		{
		  myTime=nSysTime-StartTime;
		  playSound(soundBeepBeep);
		}
	  // New start and destination positions in next loop iteration
	  startXPos = 3;
	  startYPos = 7;
	  destXPos = 1;
	  destYPos = 1;
	}
	sleep(3000);
}

/* Function that takes two short variables and string as arguments
 * and allows user to set values of that variables by menu on robot's display
*/
void choosePosition(short *posX, short *posY, char *text)
{
	short menuPos 			= 0;
	bool buttonPressed 	= false;
	bool enterPressed 	= false;
	bool xDirectionSet 	= false;
	bool yDirectionSet 	= false;
	bool directionSet 	= false;
	bool prompt = false;

	while(!directionSet)
	{
		if(!xDirectionSet)
		{
			if(!prompt)
			{
				eraseDisplay();
				displayCenteredTextLine(3, "Choose X %s axis position:", text);
				sleep(1500);
				eraseDisplay();
				prompt = true;
			}

			switch(menuPos)
			{
				case 1:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 2:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 3:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 4:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 5:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 6:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 7:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 8:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
				case 9:
					displayCenteredBigTextLine(3, "X: %d Y: %d", menuPos, *posX);
					break;
			}

			if(getButtonPress(buttonUp) && !buttonPressed)
			{
				menuPos--;
				if(menuPos < 0)
					menuPos = 0;
				buttonPressed = true;
				eraseDisplay();
			}
			if(getButtonPress(buttonDown) && !buttonPressed)
			{
				menuPos++;
				if(menuPos > 9)
					menuPos = 9;
				buttonPressed = true;
				eraseDisplay();
			}
			if(!getButtonPress(buttonDown) && !getButtonPress(buttonUp)  && buttonPressed)
			{
				buttonPressed = false;
			}

			if(getButtonPress(buttonEnter) && !enterPressed)
			{
				*posX = menuPos;
				enterPressed = true;
				xDirectionSet = true;
				prompt = false;
			}
		}
		else if(!yDirectionSet)
		{
			if(!prompt)
			{
				menuPos = 0;
				eraseDisplay();
				displayCenteredTextLine(3, "Choose Y %s axis position:", text);
				sleep(1500);
				eraseDisplay();
				enterPressed = false;
				buttonPressed = false;
				prompt = true;
			}


			switch(menuPos)
			{
				case 1:
					displayCenteredBigTextLine(3, "X: %d Y: %d", *posX, menuPos);
					break;
				case 2:
					displayCenteredBigTextLine(3, "X: %d Y: %d", *posX, menuPos);
					break;
				case 3:
					displayCenteredBigTextLine(3, "X: %d Y: %d", *posX, menuPos);
					break;
				case 4:
					displayCenteredBigTextLine(3, "X: %d Y: %d", *posX, menuPos);
					break;
				case 5:
					displayCenteredBigTextLine(3, "X: %d Y: %d", *posX, menuPos);
					break;
				case 6:
					displayCenteredBigTextLine(3, "X: %d Y: %d", *posX, menuPos);
					break;
				case 7:
					displayCenteredBigTextLine(3, "X: %d Y: %d", *posX, menuPos);
					break;
			}

			if(getButtonPress(buttonUp) && !buttonPressed)
			{
				menuPos--;
				if(menuPos < 0)
					menuPos = 0;
				buttonPressed = true;
				eraseDisplay();
			}
			if(getButtonPress(buttonDown) && !buttonPressed)
			{
				menuPos++;
				if(menuPos > 7)
					menuPos = 7;
				buttonPressed = true;
				eraseDisplay();
			}
			if(!getButtonPress(buttonDown) && !getButtonPress(buttonUp)  && buttonPressed)
			{
				buttonPressed = false;
			}

			if(getButtonPress(buttonEnter) && !enterPressed)
			{
				*posY = menuPos;
				enterPressed = true;
				xDirectionSet = true;
				directionSet = true;
			}
		}
	}
}

/* Turn left 90 degrees */
void turnLeft90()
{
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);
		resetGyro(gyroSensor);
		sleep(400);
		while(fabs(getGyroDegrees(gyroSensor)) < 89)
		{
			setMotorSpeed(rightMotor, 10);
			setMotorSpeed(leftMotor, -10);
			//displayCenteredBigTextLine(5, "%d@", getGyroDegrees(gyroSensor));
		}
		setMotorSpeed(rightMotor, 0);
		setMotorSpeed(leftMotor, 0);
}

/* Turn right 90 degrees */
void turnRight90()
{
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);
		resetGyro(gyroSensor);
		sleep(400);
		while(fabs(getGyroDegrees(gyroSensor)) < 89)
		{
			setMotorSpeed(rightMotor, -10);
			setMotorSpeed(leftMotor, 10);
			//displayCenteredBigTextLine(5, "%d@", getGyroDegrees(gyroSensor));
		}
		setMotorSpeed(rightMotor, 0);
		setMotorSpeed(leftMotor, 0);
}

/* Turn 180 degrees */
void turn180()
{
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);
		resetGyro(gyroSensor);
		sleep(400);
		while(fabs(getGyroDegrees(gyroSensor)) < 179)
		{
			setMotorSpeed(rightMotor, -10);
			setMotorSpeed(leftMotor, 10);
			//displayCenteredBigTextLine(5, "%d@", getGyroDegrees(gyroSensor));
		}
		setMotorSpeed(rightMotor, 0);
		setMotorSpeed(leftMotor, 0);
}
/*
*/
void dodgeObject(bool sameRow)
{
        if(sameRow == true)
        {
            turnRight90();
			drive(0, gridWidth, 30);
			turnLeft90();
			drive(0, gridWidth, 30); // Drive 2x gridh width to dodge that object
			// Finish facing start direction
        }
        else
        {
            turnRight90();
			drive(0, gridWidth, 30);
			turnLeft90();
			drive(0, 2 * gridWidth, 30); // Drive 2x gridh width to dodge that object
			turnLeft90();
			drive(0, gridWidth, 30); // go back to starting position
			turnRight90();
			// Finish facing start direction
        }
}

/* Function that drives wheels on specified distance in centimeters.
 * Function also takes nMotorRatio and motor power as arguments
 */
void drive(long nMotorRatio, float dist, long motorPower)
{
		float wheelDiameter = 5.5; // In cm
		float distanceInOneRotation = wheelDiameter * PI; //2*R*PI
		float rotations = dist / distanceInOneRotation; // How many full wheel rotations are in given distance
		setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, 360 * rotations, motorPower);
		waitUntilMotorStop(leftMotor);
		waitUntilMotorStop(rightMotor);
}
